name: Mi Flujo de Trabajo

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  prueba-escritura:
    runs-on: ubuntu-latest

    steps:
      - name: Comprobar permisos
        run: echo "GitHub Actions tiene permiso de escritura"
